const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';

const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';
const DELETE_COURSE_SUCCESS = 'DELETE_COURSE_SUCCESS';

const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';

const CREATE_AUTHOR_SUCCESS = 'CREATE_AUTHOR_SUCCESS';
const UPDATE_AUTHOR_SUCCESS = 'UPDATE_AUTHOR_SUCCESS';

const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
const END_AJAX_CALL = ' END_AJAX_CALL';
const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

const SORT_COURSE_LIST = 'SORT_COURSE_LIST';
const SORT_AUTHOR_LIST = 'SORT_AUTHOR_LIST';
const SORT = 'SORT';

export {
  LOAD_COURSES_SUCCESS,
  CREATE_COURSE_SUCCESS,
  UPDATE_COURSE_SUCCESS,
  DELETE_COURSE_SUCCESS,
  LOAD_AUTHORS_SUCCESS,
  CREATE_AUTHOR_SUCCESS,
  UPDATE_AUTHOR_SUCCESS,
  BEGIN_AJAX_CALL,
  END_AJAX_CALL,
  AJAX_CALL_ERROR,
  SORT_COURSE_LIST,
  SORT_AUTHOR_LIST,
  SORT,
};
