const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
const LOAD_COURSES_FAILURE = 'LOAD_COURSES_FAILURE';
const DELETE_COURSE = 'DELETE_COURSE';

export {
  LOAD_COURSES_SUCCESS,
  DELETE_COURSE,
  LOAD_COURSES_FAILURE,
};
